"""Run five required questions and optionally save a Markdown test log."""

import argparse
from pathlib import Path

from app.pipeline import answer_question, build_index
from app.vector_store import collection_count

TEST_QUESTIONS = [
    "Which wireless security protocols should be used, and which ones should be avoided?",
    "How long should the wireless network password be?",
    "What is Step 1 for resetting a jammed printer?",
    "What should I do if automatic email server configuration fails on Android?",
    "What is the company's vacation policy?",
]


def create_test_log(reindex: bool = False) -> str:
    if reindex or collection_count() == 0:
        build_index()

    sections = [
        "# RAG Query Test Log",
        "",
        "Generated by running five questions against three IT support guides.",
    ]
    for number, question in enumerate(TEST_QUESTIONS, start=1):
        result = answer_question(question)
        sections.extend(["", f"## Test {number}", "", f"**Question:** {question}"])
        for chunk_number, chunk in enumerate(result["chunks"], start=1):
            clean_chunk_text = "\n".join(
                line.rstrip() for line in chunk["text"].splitlines()
            )
            sections.extend(
                [
                    "",
                    f"### Retrieved chunk {chunk_number}",
                    "",
                    f"- Source: `{chunk['source']}`",
                    f"- Chunk index: `{chunk['chunk_index']}`",
                    f"- Distance: `{chunk['distance']:.4f}`",
                    "",
                    "```text",
                    clean_chunk_text,
                    "```",
                ]
            )
        sections.extend(["", "**Generated answer:**", "", result["answer"]])
    return "\n".join(sections) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the RAG submission queries.")
    parser.add_argument("--output", type=Path, help="optional Markdown output path")
    parser.add_argument(
        "--reindex",
        action="store_true",
        help="rebuild the vector index from the current data files first",
    )
    args = parser.parse_args()
    log = create_test_log(reindex=args.reindex)
    print(log)
    if args.output:
        args.output.write_text(log, encoding="utf-8")
        print(f"Saved test log to {args.output}")


if __name__ == "__main__":
    main()
